# Generated by Django 3.0.5 on 2020-12-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.CharField(max_length=100),
        ),
    ]
